#!/usr/bin/env bash
# Claude Code PreToolUse hook (Edit|Write|MultiEdit): block edits to generated
# firmware sources under firmware/main/gen/ and to firmware/test/intent_cases.h
# -- a hand edit there is silently clobbered by the next regen. Exit 2 blocks
# the call and names the regenerate command; anything else passes through.
set -uo pipefail
input=$(cat)
# Cheap substring pre-check on the raw JSON before spawning python3 for every
# Edit/Write/MultiEdit call -- only these two generated paths matter here.
case "$input" in *"firmware/main/gen/"*|*"intent_cases.h"*) ;; *) exit 0 ;; esac

root=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
cd "$root" || exit 0

f=$(printf '%s' "$input" | python3 -c '
import json, os, sys
p = json.load(sys.stdin).get("tool_input", {}).get("file_path", "")
if not p:
    sys.exit(0)
rp = os.path.relpath(os.path.abspath(p), sys.argv[1])
print("" if rp.startswith("..") else rp)
' "$root" 2>/dev/null) || exit 0
[ -z "$f" ] && exit 0

case "$f" in
  firmware/main/gen/*) ;;
  firmware/test/intent_cases.h) ;;
  *) exit 0 ;;
esac

# Name the actual regenerate command by reading the file's own "generated by
# ..." header, so this hook needs no hardcoded per-file mapping.
gen=$(head -1 "$f" 2>/dev/null | python3 -c '
import re, sys
line = sys.stdin.readline()
m = re.search(r"generated by (.+?)\s*(?:--|—)\s*do not edit", line)
print(m.group(1).strip() if m else "")
' 2>/dev/null)
[ -z "$gen" ] && gen="its generator (uv run kws-fwgen / kws-codegen / kws-export --firmware, or scripts/gen-intent-cases.py)"

echo "$f is generated -- do not hand-edit, the next regen overwrites it. Regenerate with: $gen" >&2
exit 2
