/* generated by scripts/gen-intent-cases.py from kws_de.grammar.parse() -- do not edit */
#pragma once

typedef struct {
    const char *words;
    bool valid;
    const char *device;
    const char *zone;
    const char *action;
} intent_case_t;

#define INTENT_CASE_COUNT 34
static const intent_case_t INTENT_CASES[INTENT_CASE_COUNT] = {
  {"Licht an", true, "Licht", NULL, "an"},
  {"Licht Küche an", true, "Licht", "Küche", "an"},
  {"Licht fünfzig", true, "Licht", NULL, "fünfzig"},
  {"Kühlschrank leise", true, "Kühlschrank", NULL, "leise"},
  {"Heizung wärmer", true, "Heizung", NULL, "wärmer"},
  {"Aufstelldach auf", true, "Aufstelldach", NULL, "auf"},
  {"an", false, NULL, NULL, NULL},
  {"Licht", false, NULL, NULL, NULL},
  {"an Licht", false, NULL, NULL, NULL},
  {"Küche Licht an", false, NULL, NULL, NULL},
  {"Licht Licht an", false, NULL, NULL, NULL},
  {"Licht an aus", false, NULL, NULL, NULL},
  {"Aufstelldach Küche auf", false, NULL, NULL, NULL},
  {"Kühlschrank auf", false, NULL, NULL, NULL},
  {"fünfzig", false, NULL, NULL, NULL},
  {"Licht Heizung an", false, NULL, NULL, NULL},
  {"Licht _unknown_ Küche an", true, "Licht", "Küche", "an"},
  {"_unknown_", false, NULL, NULL, NULL},
  {"", false, NULL, NULL, NULL},
  {"Küchenlicht an", true, "Licht", "Küche", "an"},
  {"Außenlicht aus", true, "Licht", "Außen", "aus"},
  {"Leselicht an", true, "Licht", "Lesen", "an"},
  {"Küchenlicht heller", true, "Licht", "Küche", "heller"},
  {"Küchenlicht", false, NULL, NULL, NULL},
  {"Licht Küchenlicht an", false, NULL, NULL, NULL},
  {"Küchenlicht Küche an", false, NULL, NULL, NULL},
  {"GuteNacht", true, "Licht", NULL, "aus"},
  {"GutenMorgen", true, "Licht", NULL, "an"},
  {"Leseratte", true, "Licht", "Lesen", "an"},
  {"Nachtlicht", true, "Licht", NULL, "fünfundzwanzig"},
  {"Licht GuteNacht", false, NULL, NULL, NULL},
  {"GuteNacht Licht", false, NULL, NULL, NULL},
  {"Leseratte Lesen", false, NULL, NULL, NULL},
  {"Nachtlicht fünfzig", false, NULL, NULL, NULL},
};
