/* generated by scripts/gen-intent-cases.py from kws_de.grammar.parse() -- do not edit */
#pragma once

typedef struct {
    const char *words;
    bool valid;
    const char *device;
    const char *zone;
    const char *action;
} intent_case_t;

#define INTENT_CASE_COUNT 41
static const intent_case_t INTENT_CASES[INTENT_CASE_COUNT] = {
  {"Licht an", true, "Licht", NULL, "an"},
  {"Licht Küche an", true, "Licht", "Küche", "an"},
  {"Licht fünfzig", true, "Licht", NULL, "fünfzig"},
  {"Kühlschrank leise", true, "Kühlschrank", NULL, "leise"},
  {"Heizung wärmer", true, "Heizung", NULL, "wärmer"},
  {"Aufstelldach auf", true, "Aufstelldach", NULL, "auf"},
  {"an", false, NULL, NULL, NULL},
  {"Licht", false, NULL, NULL, NULL},
  {"an Licht", false, NULL, NULL, NULL},
  {"Küche Licht an", false, NULL, NULL, NULL},
  {"Licht Licht an", false, NULL, NULL, NULL},
  {"Licht an aus", false, NULL, NULL, NULL},
  {"Aufstelldach Küche auf", false, NULL, NULL, NULL},
  {"Kühlschrank auf", false, NULL, NULL, NULL},
  {"fünfzig", false, NULL, NULL, NULL},
  {"Licht Heizung an", false, NULL, NULL, NULL},
  {"Licht _unknown_ Küche an", true, "Licht", "Küche", "an"},
  {"_unknown_", false, NULL, NULL, NULL},
  {"", false, NULL, NULL, NULL},
  {"Küchenlicht an", true, "Licht", "Küche", "an"},
  {"Außenlicht aus", true, "Licht", "Außen", "aus"},
  {"Leselicht an", true, "Licht", "Lesen", "an"},
  {"Küchenlicht heller", true, "Licht", "Küche", "heller"},
  {"Küchenlicht", false, NULL, NULL, NULL},
  {"Licht Küchenlicht an", false, NULL, NULL, NULL},
  {"Küchenlicht Küche an", false, NULL, NULL, NULL},
  {"GuteNacht", true, "Licht", NULL, "aus"},
  {"GutenMorgen", true, "Licht", NULL, "an"},
  {"Leseratte", true, "Licht", "Lesen", "an"},
  {"Nachtlicht", true, "Licht", NULL, "fünfundzwanzig"},
  {"Licht GuteNacht", false, NULL, NULL, NULL},
  {"GuteNacht Licht", false, NULL, NULL, NULL},
  {"Leseratte Lesen", false, NULL, NULL, NULL},
  {"Nachtlicht fünfzig", false, NULL, NULL, NULL},
  {"Küche Küchenlicht an", false, NULL, NULL, NULL},
  {"Außen Außenlicht aus", false, NULL, NULL, NULL},
  {"Lesen Leselicht an", false, NULL, NULL, NULL},
  {"Küchenlicht Licht an", false, NULL, NULL, NULL},
  {"Nachtlicht Licht", false, NULL, NULL, NULL},
  {"Licht Nachtlicht", false, NULL, NULL, NULL},
  {"Lesen Leseratte", false, NULL, NULL, NULL},
};

typedef struct {
    const char *words;
    const char *seconds;
    bool valid;
    const char *device;
    const char *zone;
    const char *action;
    const char *to; /* substituted label, NULL if no substitution */
} rescore_case_t;

#define RESCORE_CASE_COUNT 11
static const rescore_case_t RESCORE_CASES[RESCORE_CASE_COUNT] = {
  {"Licht _unknown_", "Licht:0.90|an:0.83", true, "Licht", NULL, "an", "an"},
  {"_unknown_ an", "Licht:0.90|an:0.83", true, "Licht", NULL, "an", "Licht"},
  {"Licht _unknown_ an", "Licht:0.90|Küche:0.80|an:0.70", true, "Licht", NULL, "an", NULL},
  {"Licht _unknown_", "Licht:0.90|an:0.10", false, NULL, NULL, NULL, NULL},
  {"Licht _unknown_", "Licht:0.90|an:0.25", true, "Licht", NULL, "an", "an"},
  {"_unknown_ _unknown_", "Licht:0.90|an:0.83", false, NULL, NULL, NULL, NULL},
  {"Licht _unknown_", "an:0.90", false, NULL, NULL, NULL, NULL},
  {"_unknown_ _unknown_ an", "_silence_:0.90|Licht:0.90|an:0.50", true, "Licht", NULL, "an", "Licht"},
  {"Licht _unknown_", "Licht:0.90|Heizung:0.90", false, NULL, NULL, NULL, NULL},
  {"Licht an", "Licht:0.90|an:0.90", true, "Licht", NULL, "an", NULL},
  {"_unknown_ _unknown_ _unknown_ _unknown_ _unknown_ _unknown_ an", "fünfundsiebzig:0.90|Licht:0.10|Licht:0.10|Licht:0.10|Licht:0.10|Licht:0.10|an:0.10", false, NULL, NULL, NULL, NULL},
};
