/* generated by scripts/gen-intent-cases.py from kws_de.grammar.parse() -- do not edit */
#pragma once

typedef struct {
    const char *words;
    bool valid;
    const char *device;
    const char *zone;
    const char *action;
} intent_case_t;

#define INTENT_CASE_COUNT 19
static const intent_case_t INTENT_CASES[INTENT_CASE_COUNT] = {
  {"Licht an", true, "Licht", NULL, "an"},
  {"Licht Küche an", true, "Licht", "Küche", "an"},
  {"Licht fünfzig", true, "Licht", NULL, "fünfzig"},
  {"Kühlschrank leise", true, "Kühlschrank", NULL, "leise"},
  {"Heizung wärmer", true, "Heizung", NULL, "wärmer"},
  {"Aufstelldach auf", true, "Aufstelldach", NULL, "auf"},
  {"an", false, NULL, NULL, NULL},
  {"Licht", false, NULL, NULL, NULL},
  {"an Licht", false, NULL, NULL, NULL},
  {"Küche Licht an", false, NULL, NULL, NULL},
  {"Licht Licht an", false, NULL, NULL, NULL},
  {"Licht an aus", false, NULL, NULL, NULL},
  {"Aufstelldach Küche auf", false, NULL, NULL, NULL},
  {"Kühlschrank auf", false, NULL, NULL, NULL},
  {"fünfzig", false, NULL, NULL, NULL},
  {"Licht Heizung an", false, NULL, NULL, NULL},
  {"Licht _unknown_ Küche an", true, "Licht", "Küche", "an"},
  {"_unknown_", false, NULL, NULL, NULL},
  {"", false, NULL, NULL, NULL},
};
