/* Host parity for the on-device grammar port (main/intent.c) against
 * kws_de.grammar.parse(): every case in intent_cases.h (generated by
 * scripts/gen-intent-cases.py from the Python grammar) must parse to the
 * same device/zone/action, or the same invalid verdict, on both sides. */
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include "intent.h"
#include "intent_cases.h"

static bool streq(const char *a, const char *b)
{
    if (!a || !b) return a == b;
    return strcmp(a, b) == 0;
}

int main(void)
{
    int bad = 0;
    for (int i = 0; i < INTENT_CASE_COUNT; i++) {
        const intent_case_t *c = &INTENT_CASES[i];
        intent_t got = intent_parse(c->words);
        bool ok = got.valid == c->valid && streq(got.device, c->device) &&
                  streq(got.zone, c->zone) && streq(got.action, c->action);
        if (!ok) {
            printf("case %d %s: got valid=%d device=%s zone=%s action=%s, want valid=%d device=%s zone=%s action=%s\n",
                   i, c->words, got.valid, got.device ? got.device : "-", got.zone ? got.zone : "-",
                   got.action ? got.action : "-", c->valid, c->device ? c->device : "-",
                   c->zone ? c->zone : "-", c->action ? c->action : "-");
            bad++;
        }
    }
    printf("intent parity: %d/%d cases mismatch\n", bad, INTENT_CASE_COUNT);
    if (bad) return 1;

    /* intent_format(): the arrow-joined text QC round-trips through normalise()
       + grammar.parse() again (kws_de/qc.py), so its exact spelling here only
       has to match kws_de.eval.intent_text's word order/level suffix, plus the
       arrow -- not be byte-identical to it. */
    char buf[64];
    intent_t zoned = intent_parse("Licht Küche an");
    int n = intent_format(&zoned, buf, sizeof buf);
    if (strcmp(buf, "Licht Küche -> an") != 0 || n != (int)strlen(buf)) {
        printf("format(zoned) = \"%s\"\n", buf);
        return 1;
    }
    intent_t level = intent_parse("Licht fünfzig");
    intent_format(&level, buf, sizeof buf);
    if (strcmp(buf, "Licht -> fünfzig Prozent") != 0) {
        printf("format(level) = \"%s\"\n", buf);
        return 1;
    }
    intent_t invalid = intent_parse("Kühlschrank auf");
    n = intent_format(&invalid, buf, sizeof buf);
    if (n != 0 || buf[0] != 0) {
        printf("format(invalid) wrote \"%s\"\n", buf);
        return 1;
    }

    /* intent_rescore(): one substitution at an "_unknown_" slot, from the
       stream decoder's second-best word for that step, completes an
       otherwise-invalid parse. */
    const char *from = NULL, *to = NULL;
    intent_t r = intent_rescore("Licht _unknown_", "Licht:0.90|an:0.83", INTENT_RESCORE_FLOOR, &from, &to);
    if (!r.valid || !streq(r.device, "Licht") || !streq(r.action, "an") ||
        !streq(from, "_unknown_") || !streq(to, "an")) {
        printf("rescore(missing action) failed: valid=%d device=%s action=%s from=%s to=%s\n",
               r.valid, r.device ? r.device : "-", r.action ? r.action : "-",
               from ? from : "-", to ? to : "-");
        return 1;
    }
    from = to = NULL;
    r = intent_rescore("_unknown_ an", "Licht:0.90|an:0.83", INTENT_RESCORE_FLOOR, &from, &to);
    if (!r.valid || !streq(r.device, "Licht") || !streq(r.action, "an")) {
        printf("rescore(missing device) failed: valid=%d device=%s action=%s\n",
               r.valid, r.device ? r.device : "-", r.action ? r.action : "-");
        return 1;
    }
    /* Below the floor: left as the plain (invalid) parse. */
    from = to = NULL;
    r = intent_rescore("Licht _unknown_", "Licht:0.90|an:0.10", INTENT_RESCORE_FLOOR, &from, &to);
    if (r.valid || from || to) {
        printf("rescore(below floor) unexpectedly valid or set from/to\n");
        return 1;
    }
    /* Two "_unknown_" slots both clearing the floor: one substitution cannot
       fix both, so the whole retry is refused. */
    from = to = NULL;
    r = intent_rescore("_unknown_ _unknown_", "Licht:0.90|an:0.83", INTENT_RESCORE_FLOOR, &from, &to);
    if (r.valid || from || to) {
        printf("rescore(two unknowns) unexpectedly valid or set from/to\n");
        return 1;
    }
    /* Already valid: rescore is a no-op (no seconds needed). */
    r = intent_rescore("Licht an", NULL, INTENT_RESCORE_FLOOR, &from, &to);
    if (!r.valid) {
        puts("rescore(already valid) broke a valid parse");
        return 1;
    }

    puts("test_intent OK");
    return 0;
}
