#!/usr/bin/env python3
"""Generate firmware/test/intent_cases.h: a fixed list of fired-word sequences run
through kws_de.grammar.parse(), committed as the ground truth firmware/test/test_intent.c
checks its C port (main/intent.c) against.

Run from the repo root: uv run python scripts/gen-intent-cases.py
"""

import pathlib

from kws_de.grammar import Intent, parse

OUT = pathlib.Path(__file__).resolve().parent.parent / "firmware/test/intent_cases.h"

# Word sequences a fired window can produce -- space-joined KWS_LABELS entries,
# in fire order. Covers: valid (no zone), valid with zone, valid brightness
# level, missing device, missing action, wrong order (zone/action before
# device), duplicate device, duplicate action, a zone on a device that takes
# none, an action the device does not support, a level without a device, two
# devices, an "_unknown_" word interleaved (dropped, not rejecting), and empty.
CASES = [
    "Licht an",
    "Licht Küche an",
    "Licht fünfzig",
    "Kühlschrank leise",
    "Heizung wärmer",
    "Aufstelldach auf",
    "an",
    "Licht",
    "an Licht",
    "Küche Licht an",
    "Licht Licht an",
    "Licht an aus",
    "Aufstelldach Küche auf",
    "Kühlschrank auf",
    "fünfzig",
    "Licht Heizung an",
    "Licht _unknown_ Küche an",
    "_unknown_",
    "",
]


def c_str(s: str | None) -> str:
    """A C string literal holding `s` verbatim (UTF-8 source, like gen/labels.h)."""
    if s is None:
        return "NULL"
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> None:
    rows = []
    for words in CASES:
        got = parse([w for w in words.split() if w])
        if isinstance(got, Intent):
            rows.append((words, True, got.device, got.zone, got.action))
        else:
            rows.append((words, False, None, None, None))

    lines = [
        "/* generated by scripts/gen-intent-cases.py from kws_de.grammar.parse() -- do not edit */",
        "#pragma once",
        "",
        "typedef struct {",
        "    const char *words;",
        "    bool valid;",
        "    const char *device;",
        "    const char *zone;",
        "    const char *action;",
        "} intent_case_t;",
        "",
        f"#define INTENT_CASE_COUNT {len(rows)}",
        "static const intent_case_t INTENT_CASES[INTENT_CASE_COUNT] = {",
    ]
    for words, valid, device, zone, action in rows:
        lines.append(
            f"  {{{c_str(words)}, {'true' if valid else 'false'}, "
            f"{c_str(device)}, {c_str(zone)}, {c_str(action)}}},"
        )
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(rows)} cases)")


if __name__ == "__main__":
    main()
