import argparse
import json
import pathlib

import numpy as np
import tensorflow as tf

from kws_de import config


def to_int8_tflite(model, rep_samples) -> bytes:
    rep = np.asarray(rep_samples, np.float32)[..., None]

    def rep_gen():
        for i in range(rep.shape[0]):
            yield [rep[i : i + 1]]

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = rep_gen
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def balanced_calibration(X, y, *, per_class: int = 20, seed: int = 0) -> np.ndarray:
    """Stratified PTQ calibration set: up to `per_class` rows per class
    (seeded pick within class), so the quantizer sees every class's
    activation range instead of whatever `X[:200]` happened to hold
    (training data is grouped by label, so a prefix slice is a handful
    of classes)."""
    rng = np.random.default_rng(seed)
    X = np.asarray(X, np.float32)
    y = np.asarray(y)
    rows = []
    for c in np.unique(y):
        idx = np.flatnonzero(y == c)
        rows.extend(rng.permutation(idx)[:per_class].tolist())
    return X[np.asarray(rows, dtype=np.int64)]


def write_c_array(tflite: bytes, path) -> None:
    body = ", ".join(str(b) for b in tflite)
    with open(path, "w") as fh:
        fh.write("// Auto-generated. Do not edit.\n")
        fh.write(f"const unsigned char g_model[] = {{{body}}};\n")
        fh.write(f"const unsigned int g_model_len = {len(tflite)};\n")


def write_model_config(tflite: bytes, path) -> dict:
    """Quantisation params + a TFLM arena estimate for firmware/main/gen/model_config.h.
    The arena is the desktop interpreter's tensor-memory peak (a proxy for
    TFLM's planner) x1.2, rounded up to 4 KB; the device logs the real
    `arena_used_bytes()` so the constant can be tightened later."""
    itp = tf.lite.Interpreter(model_content=tflite)
    itp.allocate_tensors()
    inp, out = itp.get_input_details()[0], itp.get_output_details()[0]
    tensor_bytes = sum(
        int(np.prod(t["shape"])) * np.dtype(t["dtype"]).itemsize
        for t in itp.get_tensor_details()
        if len(t["shape"]) and t["dtype"] == np.int8
    )
    arena = -(-int(tensor_bytes * 1.2) // 4096) * 4096
    lines = [
        "/* generated by kws-export --firmware — do not edit */",
        "#pragma once",
        f"#define KWS_MODEL_INPUT_SCALE {inp['quantization'][0]:.8e}f",
        f"#define KWS_MODEL_INPUT_ZERO_POINT {int(inp['quantization'][1])}",
        f"#define KWS_MODEL_OUTPUT_SCALE {out['quantization'][0]:.8e}f",
        f"#define KWS_MODEL_OUTPUT_ZERO_POINT {int(out['quantization'][1])}",
        f"#define KWS_MODEL_ARENA_BYTES {arena}",
        f"#define KWS_MODEL_NUM_CLASSES {int(out['shape'][-1])}",
    ]
    pathlib.Path(path).write_text("\n".join(lines) + "\n")
    return {"arena_bytes": arena, "input_scale": float(inp["quantization"][0])}


def write_metadata(path, labels=None) -> None:
    meta = {
        "labels": list(labels) if labels is not None else config.LABELS,
        "mfcc": {
            "n_mfcc": config.N_MFCC,
            "n_frames": config.N_FRAMES,
            "win": config.WIN_SAMPLES,
            "hop": config.HOP_SAMPLES,
            "n_mels": config.N_MELS,
            "sample_rate": config.SAMPLE_RATE,
        },
        "budgets": {
            "model_bytes": config.MAX_MODEL_BYTES,
            "arena_bytes": config.MAX_ARENA_BYTES,
            "macs": config.MAX_MACS,
        },
    }
    with open(path, "w") as fh:
        json.dump(meta, fh, indent=2, ensure_ascii=False)


def main() -> None:  # pragma: no cover - I/O wrapper
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(config.MODELS_DIR))
    ap.add_argument("--v2", action="store_true", help="export the v2 command model (23 classes)")
    ap.add_argument(
        "--firmware",
        action="store_true",
        help="also write firmware/main/gen/{model_data,model_config}.h (implies --v2)",
    )
    args = ap.parse_args()
    if args.firmware:
        args.v2 = True
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    model_name = "command.keras" if args.v2 else "kws.keras"
    prefix = "features_v2" if args.v2 else "features"
    tflite_name = "command.tflite" if args.v2 else "model.tflite"
    header_name = "command_data.h" if args.v2 else "model_data.h"
    labels = config.COMMAND_LABELS if args.v2 else config.LABELS
    model = tf.keras.models.load_model(config.MODELS_DIR / model_name)
    d = np.load(config.DATA_DIR / f"{prefix}_train.npz")
    blob = to_int8_tflite(model, balanced_calibration(d["X"], d["y"]))
    (out / tflite_name).write_bytes(blob)
    write_c_array(blob, out / header_name)
    write_metadata(out / ("command_metadata.json" if args.v2 else "metadata.json"), labels=labels)
    write_metadata(out / "metadata.json")
    if args.firmware:
        gen = pathlib.Path("firmware/main/gen")
        gen.mkdir(parents=True, exist_ok=True)
        write_c_array(blob, gen / "model_data.h")
        write_model_config(blob, gen / "model_config.h")
