import os
import sys

# See kws_de/train.py for why: loading a tfmot-quantised (QAT) model back
# requires the legacy-Keras runtime tfmot targets, and the env var that
# selects it must be set before `tensorflow` is imported anywhere in the
# process. No-op for every export that isn't `--qat`.
if "--qat" in sys.argv and os.environ.get("TF_USE_LEGACY_KERAS") != "1":
    os.environ["TF_USE_LEGACY_KERAS"] = "1"
    os.execv(sys.executable, [sys.executable, "-m", "kws_de.export", *sys.argv[1:]])

import argparse  # noqa: E402
import datetime  # noqa: E402
import hashlib  # noqa: E402
import json  # noqa: E402
import pathlib  # noqa: E402

import numpy as np  # noqa: E402
import tensorflow as tf  # noqa: E402

from kws_de import config  # noqa: E402


def to_int8_tflite(model, rep_samples) -> bytes:
    rep = np.asarray(rep_samples, np.float32)[..., None]

    def rep_gen():
        for i in range(rep.shape[0]):
            yield [rep[i : i + 1]]

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = rep_gen
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def balanced_calibration(X, y, *, per_class: int = 20, seed: int = 0) -> np.ndarray:
    """Stratified PTQ calibration set: up to `per_class` rows per class
    (seeded pick within class), so the quantizer sees every class's
    activation range instead of whatever `X[:200]` happened to hold
    (training data is grouped by label, so a prefix slice is a handful
    of classes)."""
    rng = np.random.default_rng(seed)
    X = np.asarray(X, np.float32)
    y = np.asarray(y)
    rows = []
    for c in np.unique(y):
        idx = np.flatnonzero(y == c)
        rows.extend(rng.permutation(idx)[:per_class].tolist())
    return X[np.asarray(rows, dtype=np.int64)]


# TFLM's memory planner reuses buffers between nodes, so the desktop
# interpreter's sum of all int8 tensors — what this generator used to scale by
# 1.2 — overestimates the real arena by about 2.5x (116 KB vs the 55 KB the
# device reports for the command model). That slack was the reason the command
# arena would not fit internal SRAM and had to sit in PSRAM, which is the
# single biggest cost on Invoke. These are the device's own logged
# `arena_used_bytes()` rounded up for headroom; AllocateTensors() fails loudly
# at boot, and the firmware logs "arena used X / Y", if a future model outgrows
# them.
COMMAND_ARENA_BYTES = 65536  # device reports 55,024 B used
WAKE_ARENA_BYTES = 40960  # device reports 31,396 B used


def model_stamp(blob: bytes, source) -> str:
    """`<file name>@<first 8 hex of sha256> <mtime as YYYY-MM-DD>`.

    Baked into the generated config headers so the device can say which model
    it is actually running. A firmware image outlives the checkout that built
    it, and "which model is on the CoreS3 right now" was previously answerable
    only by rebuilding and comparing bytes. The digest is over the exact
    flatbuffer that becomes the C array, so the stamp changes when and only
    when the model does.
    """
    source = pathlib.Path(source)
    day = datetime.date.fromtimestamp(source.stat().st_mtime).isoformat()
    return f"{source.name}@{hashlib.sha256(blob).hexdigest()[:8]} {day}"


def write_c_array(tflite: bytes, path, name: str = "g_model") -> None:
    body = ", ".join(str(b) for b in tflite)
    with open(path, "w") as fh:
        fh.write("// Auto-generated. Do not edit.\n")
        fh.write(f"const unsigned char {name}[] = {{{body}}};\n")
        fh.write(f"const unsigned int {name}_len = {len(tflite)};\n")


def write_model_config(tflite: bytes, path, source) -> dict:
    """Quantisation params + the TFLM arena size for firmware/main/gen/model_config.h.

    The arena is COMMAND_ARENA_BYTES — the device's measured `arena_used_bytes()`
    plus headroom. The desktop interpreter's sum-of-tensors is still printed so
    a model that grows past the pinned size is visible at export time as well as
    at boot."""
    itp = tf.lite.Interpreter(model_content=tflite)
    itp.allocate_tensors()
    inp, out = itp.get_input_details()[0], itp.get_output_details()[0]
    tensor_bytes = sum(
        int(np.prod(t["shape"])) * np.dtype(t["dtype"]).itemsize
        for t in itp.get_tensor_details()
        if len(t["shape"]) and t["dtype"] == np.int8
    )
    arena = COMMAND_ARENA_BYTES
    print(f"command arena {arena} B (desktop sum-of-tensors {tensor_bytes} B)")
    lines = [
        "/* generated by kws-export --firmware — do not edit */",
        "#pragma once",
        f"#define KWS_MODEL_INPUT_SCALE {inp['quantization'][0]:.8e}f",
        f"#define KWS_MODEL_INPUT_ZERO_POINT {int(inp['quantization'][1])}",
        f"#define KWS_MODEL_OUTPUT_SCALE {out['quantization'][0]:.8e}f",
        f"#define KWS_MODEL_OUTPUT_ZERO_POINT {int(out['quantization'][1])}",
        f"#define KWS_MODEL_ARENA_BYTES {arena}",
        f"#define KWS_MODEL_NUM_CLASSES {int(out['shape'][-1])}",
        f'#define KWS_MODEL_ID "{model_stamp(tflite, source)}"',
        f"#define KWS_MODEL_BYTES {len(tflite)}",
    ]
    pathlib.Path(path).write_text("\n".join(lines) + "\n")
    return {"arena_bytes": arena, "input_scale": float(inp["quantization"][0])}


def write_wake_config(tflite: bytes, path, source) -> dict:
    """Quantisation params + arena estimate for firmware/main/gen/wake_model_config.h.

    The "Hey Bus" model is a microWakeWord *streaming* model: it is trained
    elsewhere (models/hey_bus.tflite) and only read here. Its input is
    [1, frames, 40] int8 spectrogram rows and its output a single uint8
    probability (prob = q * scale + zero_point, i.e. q/256). The arena is
    WAKE_ARENA_BYTES — the device's measured `arena_used_bytes()` plus headroom,
    which for this streaming graph is larger than the desktop peak because
    TFLM also plans the ring buffers it keeps as resource variables."""
    itp = tf.lite.Interpreter(model_content=tflite)
    itp.allocate_tensors()
    inp, out = itp.get_input_details()[0], itp.get_output_details()[0]
    tensor_bytes = sum(
        int(np.prod(t["shape"])) * np.dtype(t["dtype"]).itemsize
        for t in itp.get_tensor_details()
        if len(t["shape"]) and t["dtype"] in (np.int8, np.uint8)
    )
    arena = WAKE_ARENA_BYTES
    print(f"wake arena {arena} B (desktop sum-of-tensors {tensor_bytes} B)")
    frames, features = int(inp["shape"][1]), int(inp["shape"][2])
    lines = [
        "/* generated by kws-export --firmware from models/hey_bus.tflite — do not edit */",
        "#pragma once",
        f"#define KWS_WAKE_INPUT_SCALE {inp['quantization'][0]:.8e}f",
        f"#define KWS_WAKE_INPUT_ZERO_POINT {int(inp['quantization'][1])}",
        f"#define KWS_WAKE_OUTPUT_SCALE {out['quantization'][0]:.8e}f",
        f"#define KWS_WAKE_OUTPUT_ZERO_POINT {int(out['quantization'][1])}",
        f"#define KWS_WAKE_ARENA_BYTES {arena}",
        f"#define KWS_WAKE_FRAMES {frames}",
        f"#define KWS_WAKE_FEATURES {features}",
        f'#define KWS_WAKE_MODEL_ID "{model_stamp(tflite, source)}"',
        f"#define KWS_WAKE_MODEL_BYTES {len(tflite)}",
    ]
    pathlib.Path(path).write_text("\n".join(lines) + "\n")
    return {"arena_bytes": arena, "frames": frames, "features": features}


def write_wake_headers(tflite_path, gen_dir) -> dict | None:
    """Emit gen/wake_model_{data,config}.h from a microWakeWord tflite.
    Returns None (with a warning) if the model file is absent — the wake mode
    is optional and the rest of the firmware export must not depend on it."""
    tflite_path = pathlib.Path(tflite_path)
    if not tflite_path.exists():
        print(f"WARNING: {tflite_path} absent — skipping wake model headers")
        return None
    blob = tflite_path.read_bytes()
    gen_dir = pathlib.Path(gen_dir)
    write_c_array(blob, gen_dir / "wake_model_data.h", name="g_wake_model")
    info = write_wake_config(blob, gen_dir / "wake_model_config.h", tflite_path)
    print(
        f"wake model: {len(blob)} B, arena {info['arena_bytes']} B, "
        f"input {info['frames']}x{info['features']}"
    )
    return info


def write_metadata(path, labels=None) -> None:
    meta = {
        "labels": list(labels) if labels is not None else config.LABELS,
        "mfcc": {
            "n_mfcc": config.N_MFCC,
            "n_frames": config.N_FRAMES,
            "win": config.WIN_SAMPLES,
            "hop": config.HOP_SAMPLES,
            "n_mels": config.N_MELS,
            "sample_rate": config.SAMPLE_RATE,
        },
        "budgets": {
            "model_bytes": config.MAX_MODEL_BYTES,
            "arena_bytes": config.MAX_ARENA_BYTES,
            "macs": config.MAX_MACS,
        },
    }
    with open(path, "w") as fh:
        json.dump(meta, fh, indent=2, ensure_ascii=False)


def assert_model_healthy(y_true, y_pred, *, min_accuracy=0.5, min_predicted_classes=10) -> dict:
    """Refuse to ship a model that classifies at ~random or has collapsed onto a
    handful of classes. A broken `command.keras` (mode-collapsed — ~random
    accuracy even on its own training data, every input mapped to ~3 classes) was
    once exported into the firmware header unnoticed and the on-device recogniser
    produced near-uniform garbage. This gate turns that into a hard export-time
    failure. Pure over (y_true, y_pred) so it is trivially testable."""
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    accuracy = float(np.mean(y_pred == y_true))
    predicted_classes = int(np.unique(y_pred).size)
    if accuracy < min_accuracy:
        raise ValueError(
            f"model accuracy {accuracy:.1%} is below the {min_accuracy:.0%} floor "
            "— refusing to export a broken model"
        )
    if predicted_classes < min_predicted_classes:
        raise ValueError(
            f"model predicted only {predicted_classes} distinct classes (mode collapse) "
            "— refusing to export"
        )
    return {"accuracy": accuracy, "predicted_classes": predicted_classes}


def _tflite_predict(tflite: bytes, X) -> np.ndarray:  # pragma: no cover - needs tflite runtime
    """Argmax class predictions of an INT8 tflite over feature rows `X`."""
    itp = tf.lite.Interpreter(model_content=tflite)
    itp.allocate_tensors()
    inp, out = itp.get_input_details()[0], itp.get_output_details()[0]
    scale, zp = inp["quantization"]
    preds = np.empty(len(X), dtype=np.int64)
    for i in range(len(X)):
        q = np.round(X[i] / scale + zp).astype(np.int8).reshape(inp["shape"])
        itp.set_tensor(inp["index"], q)
        itp.invoke()
        preds[i] = int(itp.get_tensor(out["index"])[0].argmax())
    return preds


def main() -> None:  # pragma: no cover - I/O wrapper
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(config.MODELS_DIR))
    ap.add_argument("--v2", action="store_true", help="export the v2 command model (23 classes)")
    ap.add_argument(
        "--firmware",
        action="store_true",
        help="also write firmware/main/gen/{model_data,model_config,wake_model_data,"
        "wake_model_config}.h (implies --v2)",
    )
    ap.add_argument("--prefix", default=None, help="npz prefix (default: features[_v2])")
    ap.add_argument("--model", default=None, help="model filename (default: kws/command.keras)")
    ap.add_argument(
        "--qat",
        action="store_true",
        help="load a quantisation-aware-trained model (kws-train --qat's SavedModel "
        "dir, default <model>_qat) and use its baked-in fake-quant ranges for the "
        "INT8 conversion, instead of a plain float model + post-training "
        "quantisation; output artefacts get an extra _qat suffix",
    )
    ap.add_argument(
        "--width",
        type=int,
        default=32,
        help="conv/depthwise-separable channel count the model was built with "
        "(default 32, the shipped size); non-default widths get a _w<N> suffix "
        "on every output artefact",
    )
    ap.add_argument(
        "--stats",
        action="store_true",
        help="print params and MACs of the exported model (kws_de.budgets.estimate_macs) "
        "and exit without writing any files",
    )
    args = ap.parse_args()
    if args.firmware:
        args.v2 = True
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    model_name = args.model or ("command.keras" if args.v2 else "kws.keras")
    if args.qat:
        model_name = model_name.removesuffix(".keras") + "_qat"
    prefix = args.prefix or ("features_v2" if args.v2 else "features")
    # A v3 export must not overwrite the shipped v2 artefacts: the prefix's suffix
    # names them too (features_v3 -> command_v3.tflite / command_v3_data.h /
    # command_v3_metadata.json), and `kws-eval --prefix` loads the same name back.
    # Stock names are unchanged when --prefix is omitted (suffix ""), and the
    # firmware header path below stays fixed on purpose.
    suffix = prefix.removeprefix("features")
    if suffix == "_v2" or not args.v2:  # v2 IS the stock command model: no suffix
        suffix = ""
    if args.width != 32:
        suffix += f"_w{args.width}"
    if args.qat:
        suffix += "_qat"
    qat_tag = "_qat" if args.qat else ""
    tflite_name = f"command{suffix}.tflite" if args.v2 else f"model{qat_tag}.tflite"
    header_name = f"command{suffix}_data.h" if args.v2 else f"model{qat_tag}_data.h"
    labels = config.COMMAND_LABELS if args.v2 else config.LABELS
    if args.qat:
        import tensorflow_model_optimization as tfmot

        with tfmot.quantization.keras.quantize_scope():
            model = tf.keras.models.load_model(config.MODELS_DIR / model_name)
    else:
        model = tf.keras.models.load_model(config.MODELS_DIR / model_name)
    if args.stats:
        from kws_de.budgets import estimate_macs

        macs = estimate_macs(model)
        params = model.count_params()
        print(f"[stats] {model_name}: {params:,} params, {macs:,} MACs")
        return
    d = np.load(config.DATA_DIR / f"{prefix}_train.npz")
    blob = to_int8_tflite(model, balanced_calibration(d["X"], d["y"]))
    test_path = config.DATA_DIR / f"{prefix}_test.npz"
    if test_path.exists():
        t = np.load(test_path)
        acc = float((_tflite_predict(blob, t["X"]) == t["y"]).mean())
        print(f"INT8 test accuracy: {acc:.4f}")
    (out / tflite_name).write_bytes(blob)
    write_c_array(blob, out / header_name)
    print(f"[export] wrote {tflite_name} + {header_name} from {model_name} ({prefix})")
    write_metadata(
        out / (f"command{suffix}_metadata.json" if args.v2 else "metadata.json"), labels=labels
    )
    write_metadata(out / "metadata.json")
    if args.firmware:
        # Never bake a broken model into the firmware: validate on held-out data
        # before writing the device header. Skips only if the test split is absent.
        test_path = config.DATA_DIR / f"{prefix}_test.npz"
        if test_path.exists():
            t = np.load(test_path)
            h = assert_model_healthy(t["y"], _tflite_predict(blob, t["X"]))
            print(f"model health: {h['accuracy']:.1%} accuracy, {h['predicted_classes']} classes")
        else:
            print(f"WARNING: {test_path.name} absent — skipping model-health gate")
        gen = pathlib.Path("firmware/main/gen")
        gen.mkdir(parents=True, exist_ok=True)
        write_c_array(blob, gen / "model_data.h")
        write_model_config(blob, gen / "model_config.h", out / tflite_name)
        write_wake_headers(config.MODELS_DIR / "hey_bus.tflite", gen)


if __name__ == "__main__":  # pragma: no cover
    main()
