import argparse
import json
import pathlib

import numpy as np
import tensorflow as tf

from kws_de import config


def to_int8_tflite(model, rep_samples) -> bytes:
    rep = np.asarray(rep_samples, np.float32)[..., None]

    def rep_gen():
        for i in range(rep.shape[0]):
            yield [rep[i : i + 1]]

    conv = tf.lite.TFLiteConverter.from_keras_model(model)
    conv.optimizations = [tf.lite.Optimize.DEFAULT]
    conv.representative_dataset = rep_gen
    conv.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    conv.inference_input_type = tf.int8
    conv.inference_output_type = tf.int8
    return conv.convert()


def balanced_calibration(X, y, *, per_class: int = 20, seed: int = 0) -> np.ndarray:
    """Stratified PTQ calibration set: up to `per_class` rows per class
    (seeded pick within class), so the quantizer sees every class's
    activation range instead of whatever `X[:200]` happened to hold
    (training data is grouped by label, so a prefix slice is a handful
    of classes)."""
    rng = np.random.default_rng(seed)
    X = np.asarray(X, np.float32)
    y = np.asarray(y)
    rows = []
    for c in np.unique(y):
        idx = np.flatnonzero(y == c)
        rows.extend(rng.permutation(idx)[:per_class].tolist())
    return X[np.asarray(rows, dtype=np.int64)]


def write_c_array(tflite: bytes, path) -> None:
    body = ", ".join(str(b) for b in tflite)
    with open(path, "w") as fh:
        fh.write("// Auto-generated. Do not edit.\n")
        fh.write(f"const unsigned char g_model[] = {{{body}}};\n")
        fh.write(f"const unsigned int g_model_len = {len(tflite)};\n")


def write_model_config(tflite: bytes, path) -> dict:
    """Quantisation params + a TFLM arena estimate for firmware/main/gen/model_config.h.
    The arena is the desktop interpreter's tensor-memory peak (a proxy for
    TFLM's planner) x1.2, rounded up to 4 KB; the device logs the real
    `arena_used_bytes()` so the constant can be tightened later."""
    itp = tf.lite.Interpreter(model_content=tflite)
    itp.allocate_tensors()
    inp, out = itp.get_input_details()[0], itp.get_output_details()[0]
    tensor_bytes = sum(
        int(np.prod(t["shape"])) * np.dtype(t["dtype"]).itemsize
        for t in itp.get_tensor_details()
        if len(t["shape"]) and t["dtype"] == np.int8
    )
    arena = -(-int(tensor_bytes * 1.2) // 4096) * 4096
    lines = [
        "/* generated by kws-export --firmware — do not edit */",
        "#pragma once",
        f"#define KWS_MODEL_INPUT_SCALE {inp['quantization'][0]:.8e}f",
        f"#define KWS_MODEL_INPUT_ZERO_POINT {int(inp['quantization'][1])}",
        f"#define KWS_MODEL_OUTPUT_SCALE {out['quantization'][0]:.8e}f",
        f"#define KWS_MODEL_OUTPUT_ZERO_POINT {int(out['quantization'][1])}",
        f"#define KWS_MODEL_ARENA_BYTES {arena}",
        f"#define KWS_MODEL_NUM_CLASSES {int(out['shape'][-1])}",
    ]
    pathlib.Path(path).write_text("\n".join(lines) + "\n")
    return {"arena_bytes": arena, "input_scale": float(inp["quantization"][0])}


def write_metadata(path, labels=None) -> None:
    meta = {
        "labels": list(labels) if labels is not None else config.LABELS,
        "mfcc": {
            "n_mfcc": config.N_MFCC,
            "n_frames": config.N_FRAMES,
            "win": config.WIN_SAMPLES,
            "hop": config.HOP_SAMPLES,
            "n_mels": config.N_MELS,
            "sample_rate": config.SAMPLE_RATE,
        },
        "budgets": {
            "model_bytes": config.MAX_MODEL_BYTES,
            "arena_bytes": config.MAX_ARENA_BYTES,
            "macs": config.MAX_MACS,
        },
    }
    with open(path, "w") as fh:
        json.dump(meta, fh, indent=2, ensure_ascii=False)


def assert_model_healthy(y_true, y_pred, *, min_accuracy=0.5, min_predicted_classes=10) -> dict:
    """Refuse to ship a model that classifies at ~random or has collapsed onto a
    handful of classes. A broken `command.keras` (mode-collapsed — ~random
    accuracy even on its own training data, every input mapped to ~3 classes) was
    once exported into the firmware header unnoticed and the on-device recogniser
    produced near-uniform garbage. This gate turns that into a hard export-time
    failure. Pure over (y_true, y_pred) so it is trivially testable."""
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    accuracy = float(np.mean(y_pred == y_true))
    predicted_classes = int(np.unique(y_pred).size)
    if accuracy < min_accuracy:
        raise ValueError(
            f"model accuracy {accuracy:.1%} is below the {min_accuracy:.0%} floor "
            "— refusing to export a broken model"
        )
    if predicted_classes < min_predicted_classes:
        raise ValueError(
            f"model predicted only {predicted_classes} distinct classes (mode collapse) "
            "— refusing to export"
        )
    return {"accuracy": accuracy, "predicted_classes": predicted_classes}


def _tflite_predict(tflite: bytes, X) -> np.ndarray:  # pragma: no cover - needs tflite runtime
    """Argmax class predictions of an INT8 tflite over feature rows `X`."""
    itp = tf.lite.Interpreter(model_content=tflite)
    itp.allocate_tensors()
    inp, out = itp.get_input_details()[0], itp.get_output_details()[0]
    scale, zp = inp["quantization"]
    preds = np.empty(len(X), dtype=np.int64)
    for i in range(len(X)):
        q = np.round(X[i] / scale + zp).astype(np.int8).reshape(inp["shape"])
        itp.set_tensor(inp["index"], q)
        itp.invoke()
        preds[i] = int(itp.get_tensor(out["index"])[0].argmax())
    return preds


def main() -> None:  # pragma: no cover - I/O wrapper
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(config.MODELS_DIR))
    ap.add_argument("--v2", action="store_true", help="export the v2 command model (23 classes)")
    ap.add_argument(
        "--firmware",
        action="store_true",
        help="also write firmware/main/gen/{model_data,model_config}.h (implies --v2)",
    )
    ap.add_argument("--prefix", default=None, help="npz prefix (default: features[_v2])")
    ap.add_argument("--model", default=None, help="model filename (default: kws/command.keras)")
    args = ap.parse_args()
    if args.firmware:
        args.v2 = True
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    model_name = args.model or ("command.keras" if args.v2 else "kws.keras")
    prefix = args.prefix or ("features_v2" if args.v2 else "features")
    # A v3 export must not overwrite the shipped v2 artefacts: the prefix's suffix
    # names them too (features_v3 -> command_v3.tflite / command_v3_data.h /
    # command_v3_metadata.json), and `kws-eval --prefix` loads the same name back.
    # Stock names are unchanged when --prefix is omitted (suffix ""), and the
    # firmware header path below stays fixed on purpose.
    suffix = prefix.removeprefix("features")
    if suffix == "_v2" or not args.v2:  # v2 IS the stock command model: no suffix
        suffix = ""
    tflite_name = f"command{suffix}.tflite" if args.v2 else "model.tflite"
    header_name = f"command{suffix}_data.h" if args.v2 else "model_data.h"
    labels = config.COMMAND_LABELS if args.v2 else config.LABELS
    model = tf.keras.models.load_model(config.MODELS_DIR / model_name)
    d = np.load(config.DATA_DIR / f"{prefix}_train.npz")
    blob = to_int8_tflite(model, balanced_calibration(d["X"], d["y"]))
    (out / tflite_name).write_bytes(blob)
    write_c_array(blob, out / header_name)
    print(f"[export] wrote {tflite_name} + {header_name} from {model_name} ({prefix})")
    write_metadata(
        out / (f"command{suffix}_metadata.json" if args.v2 else "metadata.json"), labels=labels
    )
    write_metadata(out / "metadata.json")
    if args.firmware:
        # Never bake a broken model into the firmware: validate on held-out data
        # before writing the device header. Skips only if the test split is absent.
        test_path = config.DATA_DIR / f"{prefix}_test.npz"
        if test_path.exists():
            t = np.load(test_path)
            h = assert_model_healthy(t["y"], _tflite_predict(blob, t["X"]))
            print(f"model health: {h['accuracy']:.1%} accuracy, {h['predicted_classes']} classes")
        else:
            print(f"WARNING: {test_path.name} absent — skipping model-health gate")
        gen = pathlib.Path("firmware/main/gen")
        gen.mkdir(parents=True, exist_ok=True)
        write_c_array(blob, gen / "model_data.h")
        write_model_config(blob, gen / "model_config.h")
