"""TF-free generator for the firmware's config-derived headers.

Everything C must agree with Python on — labels, prompts, MFCC constant
tables, a golden MFCC vector — is emitted here as `static const` data so
`firmware/main/mfcc.c` never re-derives librosa math. `kws-export --firmware`
(model_data.h, model_config.h) is the model-derived half."""

import argparse
import pathlib

import numpy as np
import scipy.fft
import scipy.signal
from librosa.filters import mel as mel_filter

from kws_de import config, features
from kws_de.eval import build_catalog

TOP_DB = 80.0
AMIN = 1e-10
DETECTOR = {"smooth_win": 3, "threshold": 0.5, "min_consecutive": 2, "gap_steps": 2}
_TRANS = str.maketrans({"ä": "ae", "ö": "oe", "ü": "ue", "ß": "ss"})


def slug(text: str) -> str:
    s = text.lower().translate(_TRANS)
    return "-".join(w for w in "".join(c if c.isalnum() else " " for c in s).split())


def prompt_sets() -> tuple[list, list, list]:
    """(display, slug) pairs for words, sentences, negatives — in canonical
    (unshuffled) order; the device shuffles with its on-screen seed."""
    words = [(label, slug(label)) for label in config.COMMAND_LABELS if not label.startswith("_")]
    sentences = []
    for it in build_catalog():
        text = " ".join(t for t in (it.device, it.zone, it.action) if t)
        sentences.append((text, slug(text)))
    negs = [(p, slug(p)) for p in config.NEGATIVE_PROMPTS]
    return words, sentences, negs


def mfcc_tables() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Periodic Hann window, Slaney mel filterbank, ortho DCT-II rows — the
    three constant matrices librosa.feature.mfcc uses with our config."""
    win = scipy.signal.get_window("hann", config.WIN_SAMPLES, fftbins=True).astype(np.float32)
    mel = mel_filter(sr=config.SAMPLE_RATE, n_fft=config.WIN_SAMPLES, n_mels=config.N_MELS)
    dct = scipy.fft.dct(np.eye(config.N_MELS), type=2, norm="ortho", axis=0)[: config.N_MFCC]
    return win, mel.astype(np.float32), dct.astype(np.float32)


def mfcc_reference(x, win, mel, dct) -> np.ndarray:
    """Pure-numpy mirror of the C pipeline (what mfcc.c must reproduce)."""
    x = features._fit_length(x)
    n = config.N_FRAMES
    frames = np.stack(
        [x[i * config.HOP_SAMPLES : i * config.HOP_SAMPLES + config.WIN_SAMPLES] for i in range(n)]
    )
    spec = np.abs(np.fft.rfft(frames * win, axis=1)) ** 2  # (n, 241)
    logmel = 10.0 * np.log10(np.maximum(AMIN, spec @ mel.T))  # (n, 40)
    logmel = np.maximum(logmel, logmel.max() - TOP_DB)
    return (logmel @ dct.T).astype(np.float32)  # (n, 10)


# 6 significant figures = float32's honest precision. Printing more (e.g. .8e)
# exposes libm's last-ULP differences between platforms (Apple vs glibc cos/log),
# which made the CI gen-fresh diff fail against locally committed headers even at
# pinned library versions. The C side reads these as `float`, so the dropped
# digits carry no information; host MFCC parity keeps its ~55x tolerance margin.
def _c_float_rows(name, arr) -> str:
    arr = np.atleast_2d(arr)
    rows = ",\n".join("  {" + ", ".join(f"{v:.5e}f" for v in row) + "}" for row in arr)
    dims = "".join(f"[{d}]" for d in arr.shape) if arr.ndim > 1 else f"[{arr.shape[0]}]"
    if arr.shape[0] == 1 and name == "KWS_WINDOW":
        flat = ", ".join(f"{v:.5e}f" for v in np.ravel(arr))
        return f"static const float {name}[{arr.size}] = {{{flat}}};\n"
    return f"static const float {name}{dims} = {{\n{rows}\n}};\n"


def _c_strings(name, items) -> str:
    body = ",\n".join(f'  "{s}"' for s in items)
    return f"static const char *const {name}[{len(items)}] = {{\n{body}\n}};\n"


def generate(out) -> None:
    out = pathlib.Path(out)
    out.mkdir(parents=True, exist_ok=True)
    hdr = "/* generated by kws-fwgen — do not edit */\n#pragma once\n"

    labels = config.COMMAND_LABELS
    (out / "labels.h").write_text(
        hdr
        + f"#define KWS_NUM_LABELS {len(labels)}\n"
        + f"#define KWS_SILENCE_INDEX {labels.index('_silence_')}\n"
        + f"#define KWS_UNKNOWN_INDEX {labels.index('_unknown_')}\n"
        + _c_strings("KWS_LABELS", labels)
    )

    words, sentences, negs = prompt_sets()
    p = hdr
    for tag, items in (("WORD", words), ("SENTENCE", sentences), ("NEG", negs)):
        p += f"#define KWS_NUM_{tag}_PROMPTS {len(items)}\n"
        p += _c_strings(f"KWS_{tag}_PROMPTS", [d for d, _ in items])
        p += _c_strings(f"KWS_{tag}_SLUGS", [s for _, s in items])
    (out / "prompts.h").write_text(p)

    win, mel, dct = mfcc_tables()
    fc = hdr
    fc += f"#define KWS_SAMPLE_RATE {config.SAMPLE_RATE}\n#define KWS_WIN {config.WIN_SAMPLES}\n"
    fc += f"#define KWS_HOP {config.HOP_SAMPLES}\n#define KWS_N_MELS {config.N_MELS}\n"
    fc += f"#define KWS_N_MFCC {config.N_MFCC}\n#define KWS_N_FRAMES {config.N_FRAMES}\n"
    fc += f"#define KWS_N_BINS {config.WIN_SAMPLES // 2 + 1}\n"
    fc += f"#define KWS_TOP_DB {TOP_DB}f\n#define KWS_AMIN {AMIN}f\n"
    for k, v in DETECTOR.items():
        fc += f"#define KWS_{k.upper()} {v}{'f' if isinstance(v, float) else ''}\n"
    fc += (
        _c_float_rows("KWS_WINDOW", win)
        + _c_float_rows("KWS_MEL", mel)
        + _c_float_rows("KWS_DCT", dct)
    )
    (out / "features_config.h").write_text(fc)

    rng = np.random.default_rng(0)
    t = np.arange(config.CLIP_SAMPLES) / config.SAMPLE_RATE
    sig = (
        0.3 * np.sin(2 * np.pi * 440 * t)
        + 0.2 * np.sin(2 * np.pi * 1300 * t)
        + 0.05 * rng.standard_normal(t.size)
    )
    # a quarter second of digital silence exercises the top_db clamp
    sig[: config.SAMPLE_RATE // 4] = 0.0
    pcm = np.clip(np.round(sig * 32767), -32768, 32767).astype(np.int16)
    ref = mfcc_reference(pcm.astype(np.float32) / 32768.0, win, mel, dct)
    tv = hdr + "#include <stdint.h>\n"
    tv += f"static const int16_t TV_PCM[{pcm.size}] = {{{', '.join(map(str, pcm.tolist()))}}};\n"
    tv += _c_float_rows("TV_MFCC", ref)
    (out / "test_vectors.h").write_text(tv)


def main() -> None:  # pragma: no cover - I/O wrapper
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="firmware/main/gen")
    generate(ap.parse_args().out)


if __name__ == "__main__":  # pragma: no cover
    main()
